import Head from "next/head";
import { Inter } from "next/font/google";
import { GamesContainer } from "../components/GamesContainer/GamesContainer";
import { SidePanel } from "@/components/SidePanel/SidePanel";
import { SearchForm } from "@/components/SearchForm/SearchForm";
import { SortFilter } from "@/components/SortFilter/SortFilter";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const handleSubmit = (e: any) => {
    e.preventDefault();
  };

  return (
    <>
      <Head>
        <title>Game Market</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main-page">
        <SidePanel />
        <div>
          <form onSubmit={handleSubmit}>
            <SearchForm />
            <SortFilter />
          </form>
          <GamesContainer />
        </div>
      </main>
    </>
  );
}
